{% set version = "1.7.3.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-urltools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/urltools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/urltools/urltools_{{ version }}.tar.gz
  sha256: f85bb761bb85beef98d34cef0030b589bb71c24cfebc1959b5954fb0676c8772

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-triebeard                # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-triebeard
  run:
    - r-base
    - r-rcpp
    - r-triebeard

test:
  commands:
    - $R -e "library('urltools')"           # [not win]
    - "\"%R%\" -e \"library('urltools')\""  # [win]

about:
  home: https://github.com/Ironholds/urltools/
  license: MIT
  summary: A toolkit for all URL-handling needs, including encoding and decoding, parsing, parameter extraction and modification. All functions are designed to be both fast and entirely vectorised. It is intended to be useful for people dealing with web-related datasets, such as server-side logs, although may be useful for
    other situations involving large sets of URLs.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - conda-forge/r

# Package: urltools
# Type: Package
# Title: Vectorised Tools for URL Handling and Parsing
# Version: 1.7.3
# Date: 2019-04-14
# Author: Os Keyes [aut, cre], Jay Jacobs [aut, cre], Drew Schmidt [aut], Mark Greenaway [ctb], Bob Rudis [ctb], Alex Pinto [ctb], Maryam Khezrzadeh [ctb], Peter Meilstrup [ctb], Adam M. Costello [cph], Jeff Bezanson [cph], Peter Meilstrup [ctb], Xueyuan Jiang [ctb]
# Maintainer: Os Keyes <ironholds@gmail.com>
# Description: A toolkit for all URL-handling needs, including encoding and decoding, parsing, parameter extraction and modification. All functions are designed to be both fast and entirely vectorised. It is intended to be useful for people dealing with web-related datasets, such as server-side logs, although may be useful for other situations involving large sets of URLs.
# License: MIT + file LICENSE
# LazyData: TRUE
# LinkingTo: Rcpp
# Imports: Rcpp, methods, triebeard
# Suggests: testthat, knitr
# URL: https://github.com/Ironholds/urltools/
# BugReports: https://github.com/Ironholds/urltools/issues
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# Depends: R (>= 2.10)
# NeedsCompilation: yes
# Packaged: 2019-04-14 22:25:08 UTC; ironholds
# Repository: CRAN
# Date/Publication: 2019-04-14 23:02:47 UTC
