{% set version = '1.7.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-urltools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/urltools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/urltools/urltools_{{ version }}.tar.gz
  sha256: 6020355c1b16a9e3956674e5dea9ac5c035c8eb3eb6bbdd841a2b5528cafa313

build:
  merge_build_host: True  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-triebeard                # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-triebeard
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-triebeard

test:
  commands:
    - $R -e "library('urltools')"           # [not win]
    - "\"%R%\" -e \"library('urltools')\""  # [win]

about:
  home: https://github.com/Ironholds/urltools/
  license: MIT
  license_file: LICENSE
  summary: A toolkit for all URL-handling needs, including encoding and decoding, parsing, parameter
    extraction and modification. All functions are designed to be both fast and entirely
    vectorised. It is intended to be useful for people dealing with web-related datasets,
    such as server-side logs, although may be useful for other situations involving
    large sets of URLs.

extra:
  recipe-maintainers:
    - ocefpaf
    - conda-forge/r

# Package: urltools
# Type: Package
# Title: Vectorised Tools for URL Handling and Parsing
# Version: 1.7.3
# Date: 2019-04-14
# Author: Os Keyes [aut, cre], Jay Jacobs [aut, cre], Drew Schmidt [aut], Mark Greenaway [ctb], Bob Rudis [ctb], Alex Pinto [ctb], Maryam Khezrzadeh [ctb], Peter Meilstrup [ctb], Adam M. Costello [cph], Jeff Bezanson [cph], Peter Meilstrup [ctb], Xueyuan Jiang [ctb]
# Maintainer: Os Keyes <ironholds@gmail.com>
# Description: A toolkit for all URL-handling needs, including encoding and decoding, parsing, parameter extraction and modification. All functions are designed to be both fast and entirely vectorised. It is intended to be useful for people dealing with web-related datasets, such as server-side logs, although may be useful for other situations involving large sets of URLs.
# License: MIT + file LICENSE
# LazyData: TRUE
# LinkingTo: Rcpp
# Imports: Rcpp, methods, triebeard
# Suggests: testthat, knitr
# URL: https://github.com/Ironholds/urltools/
# BugReports: https://github.com/Ironholds/urltools/issues
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# Depends: R (>= 2.10)
# NeedsCompilation: yes
# Packaged: 2019-04-14 22:25:08 UTC; ironholds
# Repository: CRAN
# Date/Publication: 2019-04-14 23:02:47 UTC
