# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "J9UH1tpdzqFx8oD5olq6itqyFZmu/3ixiCb4WbtVbB9bzMniCrHyhbi5Ixrz34QmLinhSBGGH+ezuio00zp+DKYTvT0m8M46CjY44kBRV/aHIEpWsPafPXt5nmF29+j/DzrtRKc1MXjZES/6cLnWxk2dMkfcSY4hFsGq7BHy+8bdCJ29HDCE0W1YWjewarRvvcI7NoEA6FJJELIg+5JyNKvJQnG/DK2yKwRwacAnOS8lw2V3GmVrodZPs4BIY8ejEkBtbMIrUBIwH+ZkF2fCEa37XVtnkRFuRD8CBjge8EqrAjQpkezExN+SkrdVH4Ah6T31qWFtgASSNqNFw3qtFyXVsg0kcTS6dyR0dNV8T2BvUNz0pY5fDGe1SS69wtVjoi69OHqMunn0ZQdZnR4zwwWskVyQll4imNcMsIOqfUr+xa3RnsFIbv93kegZptFJQtnt53Ibzf5+M2fcP4XoC7B7JlAXm/tXOm7gRlhnSZzUsULdd4zYB2/NI01C4TKNUXjKnA4TC9lyVR3VceNq2M+fhTQ2CElw6JvaeI8lzBfUe66DA19AuerxZTXcmDkpBF/tICCwC08BeL9wtLAjVIzx5hL45mshG9H5qfGWiTWDbZ7s7PNBkyujpJK6rOd+Z7cJp+ypg5x2YLbMo5QE1Vz9CtrDOpadh4MVmMjdSYw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
