travis:
  secure:
    BINSTAR_TOKEN: J9UH1tpdzqFx8oD5olq6itqyFZmu/3ixiCb4WbtVbB9bzMniCrHyhbi5Ixrz34QmLinhSBGGH+ezuio00zp+DKYTvT0m8M46CjY44kBRV/aHIEpWsPafPXt5nmF29+j/DzrtRKc1MXjZES/6cLnWxk2dMkfcSY4hFsGq7BHy+8bdCJ29HDCE0W1YWjewarRvvcI7NoEA6FJJELIg+5JyNKvJQnG/DK2yKwRwacAnOS8lw2V3GmVrodZPs4BIY8ejEkBtbMIrUBIwH+ZkF2fCEa37XVtnkRFuRD8CBjge8EqrAjQpkezExN+SkrdVH4Ah6T31qWFtgASSNqNFw3qtFyXVsg0kcTS6dyR0dNV8T2BvUNz0pY5fDGe1SS69wtVjoi69OHqMunn0ZQdZnR4zwwWskVyQll4imNcMsIOqfUr+xa3RnsFIbv93kegZptFJQtnt53Ibzf5+M2fcP4XoC7B7JlAXm/tXOm7gRlhnSZzUsULdd4zYB2/NI01C4TKNUXjKnA4TC9lyVR3VceNq2M+fhTQ2CElw6JvaeI8lzBfUe66DA19AuerxZTXcmDkpBF/tICCwC08BeL9wtLAjVIzx5hL45mshG9H5qfGWiTWDbZ7s7PNBkyujpJK6rOd+Z7cJp+ypg5x2YLbMo5QE1Vz9CtrDOpadh4MVmMjdSYw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
