travis:
  secure:
    BINSTAR_TOKEN: t4wb4tAQdYQaifYSFkOv9zQa8uoZw13aGSLLXHXMF4+VxGeX6jvIk7+OUzZ2lpXzXgSBkQ4k8KtZy1dAMYNFShah4B+TMcLrnNNG35VJpdEW5Ww3yxXipumWN3tLbrM0jKmHZF+J5ruaZfJIBUmcbJGOHsCK+t+7ShEx3MnLFIsFrQKml8n7xttbGiGFVEEsJZkyoYXyddrpuavN/w94bsHsCTahBDLECzWkPW6qqIZCkVzkJ0k35ykWNB2NdyeupV93NFyDwCV2pYNJd3jtzpLctqGdNlbjrJfV/MFIrbKRNKcpXw4EjqkGU9QcQmOdab5ymEfTXE+/l/VSAbqcOPXxT/c9tSbLGZSyoMLdS+hhsGL65tbLaj0XwrHbSKaH8DMt7OeaXbweegD9eXB8iYK2zkIsaRGoXe/kVMoNeFjgQRD4Oqhw5KTRYJO+PgOVr587xQasiXtAE52VN8BznGqXKYlYTxFvR+8TfNZjT65BnHSCWh5g2lHulmnRBs8Rp8V15w/7mPuXQ9nEsJR4nR/TN2HLWJKzwDy1PF6B3wwu9MGq7yDztq0tKKVumv6s5+FJWLacVLfumyezUCZUm1CdqZbVku73HpkIFENzwZpUTzEHejAMq3rM8yIiMw/az/RroHUx927GI2Oy3zegxrLCDSfxtgD2/o+ketRAZgk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
